name: Automated Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'MashedPotato/**/*.cs'
      - 'MashedPotato/**/*.csproj'
      - 'MashedPotato/**/*.json'
      - 'build.ps1' # <-- This is the new line!
  workflow_dispatch:
# ... (leave the rest of the file exactly as it is)